#!/bin/bash
#
# Skript arvutab kasutaja sisestatud arvu numbrite summa
#

read -p "Sisesta suvaline täisarv: " alg_arv

arv=$alg_arv
summa=0

while [ $arv -ne 0 ]
do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done

echo "Arvu $alg_arv numbrite summa on $summa"
